# Secrets para la conexión a Google Cloud / BigQuery
# Pega esto directamente en la sección "Secrets" de Streamlit Cloud

[gcp_service_account]
type = "service_account"
project_id = "pokemon-cards-project"
private_key_id = "53479c2ebeb1d4a1f4b20d3b9f65afd7343d8864"
# La clave privada debe estar entre triples comillas dobles (""")
# para manejar correctamente los saltos de línea.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDdHAtjQEVejnV8
E8gg9nOqG0BHCCg2VUIga8JHbTU0Pt0kQh8L07jdjSgQTvKgpR7KF4Xt9y9ouQmD
bl1jz/Ga5UljKoULam4ug0XnuBYF9ec2MD75vi24QBMO1nhGBHiX12HraYYGRreL
GnziipwniyNXRtg01r5tmkGjKBXyX+XNbyp5OPTpzDEo03QFWgpIHUUnorSsNjI/
nR6h+LgfGmAcRxSC3oqpPYlqugoN04Z8XWa4ma/th7qJIe8YpN2lHc+mQ1WDBnBL
ap06nicoj+nqRm4K9GsUAMNU9A9zIzBpdtfHTzl8Ed+BTa9Q7tHX9z/cqDFTqRXM
hO2cjoO/AgMBAAECggEABLdybr2SPUAgtXLelAVt1jUam+lKok4TSQnDbS6hMeod
YYafjusHSIKYVjC48EBVdc4mpzrcoglAcLNL/rMS3lEBzcG8cM/mZcubFCRTI/Fo
6zkAPueVphaH0Ys1qZiy0dpgVls75qpfg/Ies95tElLfgB8cwZPLIB9oQwi53x+u
Z0B0R38gvWMZ5RMHtamzyZlGffA/REoHM4tIJo5tIFDlJ9fwp1+yfx1HPWljuNeF
Isd2gYoU+eEzgimlM44qFnhgcyKppo/In5Nf9fBFDdpsy0EUqZZr65+k1zdD3yW8
jaZ8nyahCaAxbloGkYCBE5uyUrnrLgHwzGZK2kUfAQKBgQD6ncIsG4AtQ8EVaql3
WkcM00ZzNbthgXyJ2pXoTb645o59KMawM1AVinq1y1iQI35PQs4u+IHNikI6Nb9J
WqNRe5U1kufgWwc2C+Hm66RgrGhoQsVfXaw/gmKo0FM7J9tSzBzJ2mzewXqcEM4b
IEsHgoIBiJX6DUzridu4Afq0wQKBgQDh3AQ+d3eL24sOhrFZ7pHPEn4sjK/NZFqH
gvieXr3mjAtvFboqkiW8wQukniqzAYtsRkSi39kpz6UziEdLy06F0erzhuJ0kNgw
eiHiYfpTdsGS7Ry5OJ6xPLrziho4kU3HwK+0Q3QVGNrS56ABak8VZFUG8vlUOJqk
4z1OZ6zYfwKBgEAHnlx2ikEGVoaKQdHkltKICC/XQpCe7Jqr5jD77AaBoVYI3PqX
oZZfUwqvcWkiKFtHzjXh+AfzkwgcQ0sShTeEQ5L0fZmsqCL+1jCRc+XfJq28oYDE
BgYT4fEPiLRMcpSs4Y4Q6E/hTtog0QfNMF4y0dRieS7xxv1Gs4RHvS4BAoGAXYhD
qarHsv9kAsv8vgVyFJLP9Zr9Ys1gQCYY11zcv5DXW1VgFykWv6giLjXh8Od+2YPw
AJM613nKLCEPhW/YQMrBxb/iH+ur28d4KMvyYoYXe8T91CaCcVt5AEn8udhSoZpG
KRyWAfadCCIrvOpNfcpi+9G7NwmJ4SbJyKJejfkCgYEAhc53udJ+wvHH0c5SaJdn
bQI2mGwx9YywKt7ep9eF/wlHGAWi57Nm9tKPfA3B826/I7Ub+zExbsUTrnCMj+V8
nebNtG4SDuQ1nQOwlc5Xu0FqQ3FFURkQhPWan5qwxNxv/BRROO9Uw6uRo6ZlkRL0o
PUcJ0XC+HF/yrcqxlcOasLU=
-----END PRIVATE KEY-----"""
client_email = "bq-access-sa@pokemon-cards-project.iam.gserviceaccount.com"
client_id = "116111802429844837871"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bq-access-sa%40pokemon-cards-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
